name: 01 - Building Blocks
on : push

jobs : 
  echo-hello : 
    runs-on : self-hosted
    steps :
      - name : "Say hello"
        run : |
          echo "Hello, World!"
          exit 0
  echo-goodbye : 
    runs-on : self-hosted
    steps : 
      - name : "Failed step"
        run : echo "I will fail"
      - name : "Say goodbye"
        run : |
          echo "I am"
          echo "a multi-line"
          echo "script."
