name: 01 - Building Blocks
on : push
runs_on : "ubuntu-latest"

jobs : 
  echo-hello : 
    steps :
      name : "Say hello"
      run : echo "Hello, World!"
  echo-goodbye : 
    steps : 
      - name : "Failed step"
        run : echo "I will fail"
      - name : "Say goodbye"
        run : |
          echo "I am"
          echo "a multi-line"
          echo "script."
