name : 02 - Workflow Events
on :
    push :
    pull_request :

jobs :
    echo_push : 
        if : github.event_name == 'push'
        runs-on : ubuntu-latest
        steps :
        - name : push trigger       
          run : "echo Hey run on push event : ${{github.event_name}}"  
    
    echo_pull_request :
        if : github.event_name == 'pull_request'
        runs-on : ubuntu-latest
        steps :
            - name : pull request trigger
              run : "echo pull request trigger : ${{github.event_name}}"
    # schedule :
    #     cron : /5 * * * * *
    #     jobs :  
    #         cron_trigger : 
    #             runs_on : ubuntu-latest
    #             steps :
    #                 - name : cron scheduler trigger
    #                   run : "echo cron runs on every 5 seconds"



