name : 07 - Using Expressions
run-name : 07 - Using Expressions | DEBUG - <'ON' if the debug input is true, 'OFF' otherwise>
on :
  push : 
  workflow_dispatch : 
    inputs : 
      debug : 
        type : boolean 
        default : false

jobs : 
  echo : 
    runs-on : ubuntu-latest
    steps : 
      - name : Print start-up data
        if: inputs.debug == true
        run : echo "debug input var is true"
      - name : Print when triggered from main
        if: github.branch == 'main'
        run : |
          echo "I was triggered from main"
          echo ${{ inputs.debug || false }}