name : 13 - Using Caching
on :  
  workflow_dispatch : 
    inputs : 
      use-cache : 
        type : boolean
        default : true
        description : "Whether to execute cache step"

jobs : 
  build : 
    runs-on : ubuntu-latest
    defaults :  
      run :
        working-directory : tetin
    steps : 
      - name : Checkout code
        run : actions/checkout@v4
      - name : Setup Node
        uses : actions/setup-node@v3
        with : 
          node-version : "20.x"
      - name : Install dependencies
        run : "npm install"
      - name : Testing
        run : "npm run test"
      - name : Building
        run : "npm run build"
      - name : Deploying to nonprod
        run : |
          echo "Deploying to nonprod"
          echo "::error:: This is sample error message"