name : 16 - Working with Environments
run-name : 16 - Working with Environments | env - ${{inputs.target-env}}
on :
  workflow_dispatch :
    inputs : 
      target-env : 
        type : environment  
        default : stage

jobs : 
  echo : 
    runs-on : ubuntu-latest
    environment : ${{inputs.target-env}}
    env : 
      my_env_var : ${{ vars.MY_ENV_VALUE || 'Default value' }}
    steps :
      - name : Echo vars 
        run : echo "Env variable: ${{env.my_env_var}}"